//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PartnerClient.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied: You must have a partner account to use this app..
        /// </summary>
        internal static string AccessDeniedNotPartner {
            get {
                return ResourceManager.GetString("AccessDeniedNotPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Projects.
        /// </summary>
        internal static string ActiveProjects {
            get {
                return ResourceManager.GetString("ActiveProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Child.
        /// </summary>
        internal static string AddChild {
            get {
                return ResourceManager.GetString("AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexis House.
        /// </summary>
        internal static string AlexisHouse {
            get {
                return ResourceManager.GetString("AlexisHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies.
        /// </summary>
        internal static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies: {0}.
        /// </summary>
        internal static string AllergiesFormat {
            get {
                return ResourceManager.GetString("AllergiesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is pending..
        /// </summary>
        internal static string ApplicationPendingMessage {
            get {
                return ResourceManager.GetString("ApplicationPendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas of Work.
        /// </summary>
        internal static string AreasOfWork {
            get {
                return ResourceManager.GetString("AreasOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Authorisation Code is {0}.
        /// </summary>
        internal static string AuthCodeFormat {
            get {
                return ResourceManager.GetString("AuthCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Error.
        /// </summary>
        internal static string AuthError {
            get {
                return ResourceManager.GetString("AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tick the relevant box for each document you are able to provide..
        /// </summary>
        internal static string AvailableDocumentsMessage {
            get {
                return ResourceManager.GetString("AvailableDocumentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type.
        /// </summary>
        internal static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type: {0}.
        /// </summary>
        internal static string BloodTypeFormat {
            get {
                return ResourceManager.GetString("BloodTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string CaptionPlaceholder {
            get {
                return ResourceManager.GetString("CaptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Details.
        /// </summary>
        internal static string ChildDetails {
            get {
                return ResourceManager.GetString("ChildDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a stronger password..
        /// </summary>
        internal static string ChooseStrongerPassword {
            get {
                return ResourceManager.GetString("ChooseStrongerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City: {0}.
        /// </summary>
        internal static string CityFormat {
            get {
                return ResourceManager.GetString("CityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Projects.
        /// </summary>
        internal static string CompletedProjects {
            get {
                return ResourceManager.GetString("CompletedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You intend to join {0}, correct?.
        /// </summary>
        internal static string ConfirmTeamFormat {
            get {
                return ResourceManager.GetString("ConfirmTeamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Info.
        /// </summary>
        internal static string CoreInfo {
            get {
                return ResourceManager.GetString("CoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Breakdown.
        /// </summary>
        internal static string CostBreakdown {
            get {
                return ResourceManager.GetString("CostBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₤ Cost.
        /// </summary>
        internal static string CostPlaceholder {
            get {
                return ResourceManager.GetString("CostPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  ×  {1}  =  ₤{2}  (₤{3} Each).
        /// </summary>
        internal static string CostSubcomponentStringFormat {
            get {
                return ResourceManager.GetString("CostSubcomponentStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country: {0}.
        /// </summary>
        internal static string CountryFormat {
            get {
                return ResourceManager.GetString("CountryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Application.
        /// </summary>
        internal static string CreateApplication {
            get {
                return ResourceManager.GetString("CreateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at {0} by {1}.
        /// </summary>
        internal static string CreatedFormat {
            get {
                return ResourceManager.GetString("CreatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Progress Update.
        /// </summary>
        internal static string CreateProgressUpdate {
            get {
                return ResourceManager.GetString("CreateProgressUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        internal static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Team.
        /// </summary>
        internal static string CreateTeam {
            get {
                return ResourceManager.GetString("CreateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current password..
        /// </summary>
        internal static string CurrentPasswordPrompt {
            get {
                return ResourceManager.GetString("CurrentPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth: {0}.
        /// </summary>
        internal static string DateOfBirthFormat {
            get {
                return ResourceManager.GetString("DateOfBirthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Entry.
        /// </summary>
        internal static string DateOfEntry {
            get {
                return ResourceManager.GetString("DateOfEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Entry: {0}.
        /// </summary>
        internal static string DateOfEntryFormat {
            get {
                return ResourceManager.GetString("DateOfEntryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this draft?.
        /// </summary>
        internal static string DeleteDraftMessage {
            get {
                return ResourceManager.GetString("DeleteDraftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Draft.
        /// </summary>
        internal static string DeleteDraftTitle {
            get {
                return ResourceManager.GetString("DeleteDraftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor / Clinic Name.
        /// </summary>
        internal static string DoctorClinicName {
            get {
                return ResourceManager.GetString("DoctorClinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor / Clinic Name: {0}.
        /// </summary>
        internal static string DoctorClinicNameFormat {
            get {
                return ResourceManager.GetString("DoctorClinicNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Applications.
        /// </summary>
        internal static string DraftApplications {
            get {
                return ResourceManager.GetString("DraftApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each.
        /// </summary>
        internal static string Each {
            get {
                return ResourceManager.GetString("Each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Progress Update.
        /// </summary>
        internal static string EditProgressUpdate {
            get {
                return ResourceManager.GetString("EditProgressUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: {0}.
        /// </summary>
        internal static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification email has been sent..
        /// </summary>
        internal static string EmailVerifSent {
            get {
                return ResourceManager.GetString("EmailVerifSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Contract.
        /// </summary>
        internal static string EmployeeContract {
            get {
                return ResourceManager.GetString("EmployeeContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Evaluation.
        /// </summary>
        internal static string EmployeeEvaluation {
            get {
                return ResourceManager.GetString("EmployeeEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        internal static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Names.
        /// </summary>
        internal static string FirstNames {
            get {
                return ResourceManager.GetString("FirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        internal static string Focus {
            get {
                return ResourceManager.GetString("Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus: {0}.
        /// </summary>
        internal static string FocusFormat {
            get {
                return ResourceManager.GetString("FocusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like a password reset email to be sent to {0} ?.
        /// </summary>
        internal static string ForgotPasswordPrompt {
            get {
                return ResourceManager.GetString("ForgotPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Partners.
        /// </summary>
        internal static string ForPartners {
            get {
                return ResourceManager.GetString("ForPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade: {0}.
        /// </summary>
        internal static string GradeFormat {
            get {
                return ResourceManager.GetString("GradeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        internal static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone: {0}.
        /// </summary>
        internal static string HomePhoneFormat {
            get {
                return ResourceManager.GetString("HomePhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact Evaluation.
        /// </summary>
        internal static string ImpactEvaluation {
            get {
                return ResourceManager.GetString("ImpactEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impact Measurement.
        /// </summary>
        internal static string ImpactMeasurement {
            get {
                return ResourceManager.GetString("ImpactMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Induction.
        /// </summary>
        internal static string Induction {
            get {
                return ResourceManager.GetString("Induction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Code.
        /// </summary>
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there isn&apos;t a team with that code!.
        /// </summary>
        internal static string InvalidCodeMessage {
            get {
                return ResourceManager.GetString("InvalidCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Profile.
        /// </summary>
        internal static string JobProfile {
            get {
                return ResourceManager.GetString("JobProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Team.
        /// </summary>
        internal static string JoinTeam {
            get {
                return ResourceManager.GetString("JoinTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids.
        /// </summary>
        internal static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Names.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Team.
        /// </summary>
        internal static string LeaveTeam {
            get {
                return ResourceManager.GetString("LeaveTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 1.
        /// </summary>
        internal static string LineOne {
            get {
                return ResourceManager.GetString("LineOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 1: {0}.
        /// </summary>
        internal static string LineOneFormat {
            get {
                return ResourceManager.GetString("LineOneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 3.
        /// </summary>
        internal static string LineThree {
            get {
                return ResourceManager.GetString("LineThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 3: {0}.
        /// </summary>
        internal static string LineThreeFormat {
            get {
                return ResourceManager.GetString("LineThreeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 2.
        /// </summary>
        internal static string LineTwo {
            get {
                return ResourceManager.GetString("LineTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 2: {0}.
        /// </summary>
        internal static string LineTwoFormat {
            get {
                return ResourceManager.GetString("LineTwoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother DPI.
        /// </summary>
        internal static string MamaDPI {
            get {
                return ResourceManager.GetString("MamaDPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother DPI: {0}.
        /// </summary>
        internal static string MamaDPIFormat {
            get {
                return ResourceManager.GetString("MamaDPIFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Requests.
        /// </summary>
        internal static string MemberRequests {
            get {
                return ResourceManager.GetString("MemberRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentoring.
        /// </summary>
        internal static string Mentoring {
            get {
                return ResourceManager.GetString("Mentoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone: {0}.
        /// </summary>
        internal static string MobilePhoneFormat {
            get {
                return ResourceManager.GetString("MobilePhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified at {0} by {1}.
        /// </summary>
        internal static string ModifiedFormat {
            get {
                return ResourceManager.GetString("ModifiedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        internal static string NameFormat {
            get {
                return ResourceManager.GetString("NameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password..
        /// </summary>
        internal static string NewPasswordPrompt {
            get {
                return ResourceManager.GetString("NewPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to show here....
        /// </summary>
        internal static string NothingToShowHere {
            get {
                return ResourceManager.GetString("NothingToShowHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Times.
        /// </summary>
        internal static string OpeningTimes {
            get {
                return ResourceManager.GetString("OpeningTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Times: {0}.
        /// </summary>
        internal static string OpeningTimesFormat {
            get {
                return ResourceManager.GetString("OpeningTimesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation Details.
        /// </summary>
        internal static string OrganisationDetails {
            get {
                return ResourceManager.GetString("OrganisationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father DPI.
        /// </summary>
        internal static string PapaDPI {
            get {
                return ResourceManager.GetString("PapaDPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father DPI: {0}.
        /// </summary>
        internal static string PapaDPIFormat {
            get {
                return ResourceManager.GetString("PapaDPIFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastoral Plan for Employees and Volunteers.
        /// </summary>
        internal static string PastoralPlan {
            get {
                return ResourceManager.GetString("PastoralPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Applications.
        /// </summary>
        internal static string PendingApplications {
            get {
                return ResourceManager.GetString("PendingApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation of Programme.
        /// </summary>
        internal static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevention.
        /// </summary>
        internal static string Prevention {
            get {
                return ResourceManager.GetString("Prevention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures and Responsabilities.
        /// </summary>
        internal static string ProceduresAndResponsabilites {
            get {
                return ResourceManager.GetString("ProceduresAndResponsabilites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme.
        /// </summary>
        internal static string Programme {
            get {
                return ResourceManager.GetString("Programme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme: {0}.
        /// </summary>
        internal static string ProgrammeFormat {
            get {
                return ResourceManager.GetString("ProgrammeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Update.
        /// </summary>
        internal static string ProgressUpdate {
            get {
                return ResourceManager.GetString("ProgressUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Complete!.
        /// </summary>
        internal static string ProjectCompleteE {
            get {
                return ResourceManager.GetString("ProjectCompleteE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Complete?.
        /// </summary>
        internal static string ProjectCompleteQ {
            get {
                return ResourceManager.GetString("ProjectCompleteQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one image..
        /// </summary>
        internal static string ProjectCreationImageHint {
            get {
                return ResourceManager.GetString("ProjectCreationImageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Description.
        /// </summary>
        internal static string ProjectDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ProjectDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string ProjectNamePlaceholder {
            get {
                return ResourceManager.GetString("ProjectNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Timeline.
        /// </summary>
        internal static string ProjectTimeline {
            get {
                return ResourceManager.GetString("ProjectTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding images for progress updates is optional but recommended..
        /// </summary>
        internal static string ProjectUpdateImageHint {
            get {
                return ResourceManager.GetString("ProjectUpdateImageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string PSInvalid {
            get {
                return ResourceManager.GetString("PSInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Strength: Medium.
        /// </summary>
        internal static string PSMedium {
            get {
                return ResourceManager.GetString("PSMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Strength: Strong.
        /// </summary>
        internal static string PSStrong {
            get {
                return ResourceManager.GetString("PSStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Strength: Weak.
        /// </summary>
        internal static string PSWeak {
            get {
                return ResourceManager.GetString("PSWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaires.
        /// </summary>
        internal static string Questionnaires {
            get {
                return ResourceManager.GetString("Questionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach.
        /// </summary>
        internal static string Reach {
            get {
                return ResourceManager.GetString("Reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference: {0}.
        /// </summary>
        internal static string ReferenceFormat {
            get {
                return ResourceManager.GetString("ReferenceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Structure based on OMRE.
        /// </summary>
        internal static string ReportStructure {
            get {
                return ResourceManager.GetString("ReportStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        internal static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Assessment.
        /// </summary>
        internal static string RiskAssessment {
            get {
                return ResourceManager.GetString("RiskAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securities.
        /// </summary>
        internal static string Securities {
            get {
                return ResourceManager.GetString("Securities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Categories.
        /// </summary>
        internal static string SelectCategories {
            get {
                return ResourceManager.GetString("SelectCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors: .
        /// </summary>
        internal static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: ₤{0}.
        /// </summary>
        internal static string TargetFormat {
            get {
                return ResourceManager.GetString("TargetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Code.
        /// </summary>
        internal static string TeamCode {
            get {
                return ResourceManager.GetString("TeamCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Team Code is {0}.
        /// </summary>
        internal static string TeamCodeFormat {
            get {
                return ResourceManager.GetString("TeamCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to join {0} is pending..
        /// </summary>
        internal static string TeamRequestPendingFormat {
            get {
                return ResourceManager.GetString("TeamRequestPendingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Plan.
        /// </summary>
        internal static string TrainingPlan {
            get {
                return ResourceManager.GetString("TrainingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make {0} the group leader?.
        /// </summary>
        internal static string TransferOwnershipMessage {
            get {
                return ResourceManager.GetString("TransferOwnershipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Ownership.
        /// </summary>
        internal static string TransferOwnershipTitle {
            get {
                return ResourceManager.GetString("TransferOwnershipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent!.
        /// </summary>
        internal static string UrgentE {
            get {
                return ResourceManager.GetString("UrgentE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent?.
        /// </summary>
        internal static string UrgentQ {
            get {
                return ResourceManager.GetString("UrgentQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits  •  Evaluation and Acknowledgement.
        /// </summary>
        internal static string VisitsEvaluationAndAcknowledgement {
            get {
                return ResourceManager.GetString("VisitsEvaluationAndAcknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits  •  Information Pack.
        /// </summary>
        internal static string VisitsInformationPage {
            get {
                return ResourceManager.GetString("VisitsInformationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits  •  Visiting Plan and Purpose.
        /// </summary>
        internal static string VisitsPlanAndPurpose {
            get {
                return ResourceManager.GetString("VisitsPlanAndPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits  •  Presentation and Tour.
        /// </summary>
        internal static string VisitsPresentationAndTour {
            get {
                return ResourceManager.GetString("VisitsPresentationAndTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits  •  Waiver Form.
        /// </summary>
        internal static string VisitsWaiverForm {
            get {
                return ResourceManager.GetString("VisitsWaiverForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers  •  Application Process.
        /// </summary>
        internal static string VolunteersApplicationProcess {
            get {
                return ResourceManager.GetString("VolunteersApplicationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers  •  Assessments and Incentives.
        /// </summary>
        internal static string VolunteersAssessmentsAndIncentives {
            get {
                return ResourceManager.GetString("VolunteersAssessmentsAndIncentives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers  •  Care and Support Plan.
        /// </summary>
        internal static string VolunteersCareAndSupportPlan {
            get {
                return ResourceManager.GetString("VolunteersCareAndSupportPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers  •  Profile.
        /// </summary>
        internal static string VolunteersProfile {
            get {
                return ResourceManager.GetString("VolunteersProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers  •  SelectionProcess.
        /// </summary>
        internal static string VolunteersSelectionProcess {
            get {
                return ResourceManager.GetString("VolunteersSelectionProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers  •  Training Plan.
        /// </summary>
        internal static string VolunteersTraningPlan {
            get {
                return ResourceManager.GetString("VolunteersTraningPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers  •  Values and Procedures.
        /// </summary>
        internal static string VolunteersValuesAndProcedures {
            get {
                return ResourceManager.GetString("VolunteersValuesAndProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers  •  Work Plan.
        /// </summary>
        internal static string VolunteersWorkPlan {
            get {
                return ResourceManager.GetString("VolunteersWorkPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak Password.
        /// </summary>
        internal static string WeakPassword {
            get {
                return ResourceManager.GetString("WeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Manual.
        /// </summary>
        internal static string WorkManual {
            get {
                return ResourceManager.GetString("WorkManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Plan / OMRE.
        /// </summary>
        internal static string WorkPlanOMRE {
            get {
                return ResourceManager.GetString("WorkPlanOMRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Young Boys.
        /// </summary>
        internal static string YoungBoys {
            get {
                return ResourceManager.GetString("YoungBoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Details.
        /// </summary>
        internal static string YourDetails {
            get {
                return ResourceManager.GetString("YourDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code: {0}.
        /// </summary>
        internal static string ZipCodeFormat {
            get {
                return ResourceManager.GetString("ZipCodeFormat", resourceCulture);
            }
        }
    }
}
