//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKD.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SKD.Common.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Health.
        /// </summary>
        public static string ChildHealth {
            get {
                return ResourceManager.GetString("ChildHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christian Faith.
        /// </summary>
        public static string ChristianFaith {
            get {
                return ResourceManager.GetString("ChristianFaith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Relations.
        /// </summary>
        public static string CommunityRelations {
            get {
                return ResourceManager.GetString("CommunityRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Completed  •  {0}.
        /// </summary>
        public static string CompletedProjectUpdateStringFormat {
            get {
                return ResourceManager.GetString("CompletedProjectUpdateStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructive Use Of Time.
        /// </summary>
        public static string ConstructiveUseOfTime {
            get {
                return ResourceManager.GetString("ConstructiveUseOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Relationships.
        /// </summary>
        public static string FamilyRelationships {
            get {
                return ResourceManager.GetString("FamilyRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Organisation.
        /// </summary>
        public static string ForOrganisation {
            get {
                return ResourceManager.GetString("ForOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Update.
        /// </summary>
        public static string PendingUpdate {
            get {
                return ResourceManager.GetString("PendingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Values.
        /// </summary>
        public static string PositiveValues {
            get {
                return ResourceManager.GetString("PositiveValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raised £{0} of £{1} target.
        /// </summary>
        public static string ProgressLabelFormat {
            get {
                return ResourceManager.GetString("ProgressLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Published  •  {0}.
        /// </summary>
        public static string ProjectDatePublishedStringFormat {
            get {
                return ResourceManager.GetString("ProjectDatePublishedStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update  •  {0}.
        /// </summary>
        public static string PublishedProjectUpdateStringFormat {
            get {
                return ResourceManager.GetString("PublishedProjectUpdateStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        public static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed {0}.
        /// </summary>
        public static string QuestionnaireCompletedDateStringFormat {
            get {
                return ResourceManager.GetString("QuestionnaireCompletedDateStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaires.
        /// </summary>
        public static string Questionnaires {
            get {
                return ResourceManager.GetString("Questionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Limits.
        /// </summary>
        public static string ResponsibleLimits {
            get {
                return ResourceManager.GetString("ResponsibleLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Esteem And Dreams.
        /// </summary>
        public static string SelfEsteemAndDreams {
            get {
                return ResourceManager.GetString("SelfEsteemAndDreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Identity.
        /// </summary>
        public static string SocialIdentity {
            get {
                return ResourceManager.GetString("SocialIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown - Please Update.
        /// </summary>
        public static string UnknownIMA {
            get {
                return ResourceManager.GetString("UnknownIMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string Urgent {
            get {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
    }
}
